on: 
  workflow_dispatch:

jobs:
  akto_cicd_test:
    runs-on: ubuntu-latest
    name: Test akto ci/cd
    steps:
      - uses: oren-akto/akto-github-action
        with:
          AKTO_DASHBOARD_URL: ${{secrets.AKTO_DASHBOARD_URL}}
          AKTO_API_KEY: ${{secrets.AKTO_API_KEY}}
          AKTO_TEST_CONFIGURATION: ${{secrets.AKTO_TEST_CONFIGURATION}}